#########################################
### sys-API user configuration        ###
#########################################
metricsConfig:
  monitor:
    interval: 45
    unit: SECONDS
  history:
    interval: 30
    unit: MINUTES
    purging:
      olderThan: 14
      unit: DAYS
      purgeEvery: 1
      purgeEveryUnit: DAYS
  cache:
    enabled: false
    duration: 5
    unit: SECONDS
user:
  username: user
  password: password
windows:
  enableOhmJniWrapper: true
  eventLog:
    enabled: true
  serviceManagement:
    enabled: true
linux:
  # Incorrect CPU temp on Linux? Look for log output of LinuxSensorDiscovery
  # and put the identifier below (default on intel systems is thermal:x86_pkg_temp)
  # overrideCpuTempSensor: hwmon:coretemp
  journalLogs:
    enabled: true
  systemDaemonServiceManagement:
    enabled: true
logReader:
  files: [ ]
  directories:
  # - data # sys-API data directory. You can enable log to file in application.properties
  # - /var/log # Linux log directory
# docker management and metrics support
docker:
  enabled: true
  #  cache:
  #    enabled: true
  #    duration: 2
  #    unit: SECONDS
  # uncomment if you'd like to manually specify docker host
  # host: unix:///var/run/docker.sock or unix:///run/podman/podman.sock
# resolve external IP and monitor internet connectivity
connectivityCheck:
  enabled: true
  address: https://ifconfig.me
updateCheck:
  enabled: true
  address: https://api.github.com
  user: krillsson
  repo: monitee-agent
notifications:
  ntfy:
    enabled: false
    url: "https://ntfy.sh"
    # topic: my-custom-globally-unique-topic
# advertise service in local network for easier client setup
mDNS:
  enabled: true
upnp:
  enabled: true
forwardHttpToHttps: false
graphQl:
  # print slow queries and field resolving to the log
  instrumentation: false
# Keep in mind that this feature doesn't work well with proxies
# It doesn't work domain names either
# I recommend terminating the SSL in a proxy instead, or a cloudflare tunnel
selfSignedCertificates:
  enabled: true
  ## automatically put external IP in CN
  populateCN: true
  ## automatically put internal IPs in SAN
  populateSAN: true
  ## manually populate CN and SAN below (only supports IPs)
  # commonName: 95.168.0.24
  # subjectAlternativeNames: [192.168.0.24, 10.8.0.24]